### PR TITLE
New install and uninstall script

### PR DESCRIPTION
**Pull request by AndyM48**
On further thought is seems to me that since this is written for a mobile phone, it is reasonable to install it for an individual user.
The suggested scripts therefore install the download folder to ~/.local/share/loyaltyCardOpen and also install a .desktop file.
The loyaltyCards.sh script should also point to the same folder.

I have also suggested that an uninstall script should be included in the download.

I am not sure what the setup.py script does (I don't do python :) )?

This my first pull request so I just hope that I haven't screwed things up!

### CODE REVIEW

**Comment by joanisc** [comment]
Thank you very much @fdservices!Appreciated. I'll take a look soon (I would be 2-3 days without computer) but it looks great. My approach was to leave the option to make the app self contended. So that could be executed after decompression without leaving things spread. So I though on a different methods of installation, using the script, all contended and packages for different distros. (I tried with flatpak with no success) . But maybe make sense your approach. Ah. The setup.py is to help the installation process for debian packages... Maybe there are other easier alternatives without needing a setup but that just worked for me.

**Comment by AndyM48** [comment]
OK, the install script should work on any distro, and as I said before, keep all the programs in a single directory ~/.local/share/loyaltyCardOpen, which conforms to your approach.

**Comment by chookity-pokk** [comment]
I really like the idea of an uninstalls script as well and the install script was basically pulled from Purism themselves. This setup looks fine to me because (@fdservices correct me if I'm wrong), you are basically just copying the cloned directory to `/.local/share/loyaltyCardOpen` directory. Is this common practice to keep info in that directory? Neither me nor @joanisc are debian devs, we both just have a few apps that we wanted to make for the PinePhone.

**Comment by AndyM48** [comment]
`the install script was basically pulled from Purism themselves`
No, wrote it myself, don't know anything about Purism.
`Is this common practice to keep info in that directory`
Yes, exactly that. I thought it would be a good place to keep the whole code if it is not to be installed globally. 
`Neither me nor @joanisc are debian devs,`
Nor me. I run arch linux and I too have a pinephone, hence the interest. What other apps do you have for the phone?

**Comment by chookity-pokk** [comment]
To clarify, I'm saying my install script was pulled from Purism, not yours. Thanks for the info though, I made a couple apps which can be found on my Gitlab page. Basically a white noise player and a reminder app. I'm also working on a running log app but it isn't on there yet. 

https://gitlab.com/greenbeast/elephant_remember

**Comment by AndyM48** [comment]
So sorry. I have spotted several errors in the install script. The Categories should include Utility and not Utilities and the path to the icon file is incorrect. The programme will not execute because it only runs if we are in the programme directory. To this end we will need to adjust the loyaltCards.sh script. The three lines would then read:
`Exec="$path/loyaltyCardsOpen/loyaltyCards.sh"`
`Icon="$path/loyaltyCardsOpen/loyaltycardsopen.svg"`
`Categories=GNOME;GTK;Utility;`
and the loyaltyCards shell script will have to be amended in the install script.
Not sure how to delete this Pull request and resubmit it? Edit: May be it is unnecessary? I updated the fork.

**Comment by joanisc** [comment]
Thank you very much @fdservices for the code. I like it a lot. I love bash scripts. :-) I think your changes are compatible with my approach of different installation methods including using the app without installing it (only uncompressing if you have all the dependencies). I'll accept and merge the PR and then I'll only update some spelling mistakes and update the Readme file to help other users who want to use your script by adding instruction on how to make the sh file executable (for sure most people would know it but just in case) . Good Job! Thank you

**Pull request merged**
